### ISSUE TITLE
Odd behavior of virtual devices

### ISSUE THREAD

**Issue by cu6apum** [wirenboard/wb-rules#56]
If a virtual device has a control, the requested "/on" topic is not being posted into the MQTT queue once it gets assigned a value.

Say if you toggle a switch on the web interface, you get:
/devices/vdev/controld/toggle/on 1
/devices/vdev/controls/toggle 1

whereas if you toggle it with a rule (eg, dev[vdev/toggle] = true) it posts:
/devices/vdev/controls/toggle 1

This leads to big problems sometimes. When you control a physical device using this topic, it silently refuses to operate.
For example, a relay controlled by a whenChanged rule which is tracking this topic, will not fire.

wb-rules 2.8.1

**Comment by sikmir** [comment]
Not reproduced with latest version of wb-rules.
