### ISSUE TITLE
Compilation does not generate wbgo.so

### ISSUE THREAD

**Issue by darcyg** [wirenboard/wb-rules#80]
hi wirenboard’s developer,
I use ubuntu20.04
Generate the execution file of wb rules through the Make command.
But the wbgo.so file was not generated.
It is unclear how this file was generated.
I want to use the rule engine of wb rules directly.
Used in personal home automation. Respond to such controllers as tasmota.
I hope there are clearer documents or operation procedures.
How to customize mqtt topic.
How to configure customized virtual devices, and which projects need to be compiled.
thanks.

**Comment by sikmir** [comment]
`wbgo.so` is a platform specific plugin and it's distributed only in binary form within official deb package.
